chore: fix .goreleaser.yml
- https://github.com/pressly/goose/issues/546

https://goreleaser.com/deprecations/#archivesreplacements

archives.replacements was removed from goreleaser v1.19.0.

https://github.com/pressly/goose/actions/runs/5417089392/jobs/9847661601

```
Run goreleaser/goreleaser-action@v3
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.19.1/goreleaser_Linux_x86_64.tar.gz
Extracting GoReleaser
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/059a3cc2-2697-4fe0-8c66-4ff58c7affbc -f /home/runner/work/_temp/8d49dc03-a27c-4e8e-bda2-2bc1fdb51934
GoReleaser latest installed successfully
v3.13.0 tag found for commit '26295ee'
/opt/hostedtoolcache/goreleaser-action/1.19.1/x64/goreleaser release --rm-dist
Flag --rm-dist has been deprecated, please use --clean instead
  • starting release...
  • loading config file                              file=.goreleaser.yml
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 30: field replacements not found in type config.Archive
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.19.1/x64/goreleaser' failed with exit code 1
```